#!/bin/bash
# Build Kong Gateway Configuration
# Combines modular YAML files into a single declarative kong.yml
# Usage: ./scripts/build-kong-config.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$(dirname "$SCRIPT_DIR")/config"
OUTPUT_FILE="$CONFIG_DIR/kong.yml"
TEMP_FILE="$CONFIG_DIR/kong.yml.tmp"

echo "Building Kong Gateway configuration..."
echo "Source: $CONFIG_DIR"
echo "Output: $OUTPUT_FILE"

# Start with format version and header
cat > "$TEMP_FILE" <<EOF
# Kong Gateway Declarative Configuration
# Auto-generated from modular configuration files
# DO NOT EDIT THIS FILE DIRECTLY - Edit source files and rebuild
# Build: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Build script: scripts/build-kong-config.sh

_format_version: "3.0"

EOF

# Add services section
echo "Adding services..."
echo "services:" >> "$TEMP_FILE"

# Combine all service definition files
for service_file in "$CONFIG_DIR/services"/*.yml; do
  if [ -f "$service_file" ]; then
    echo "  - Adding service from $(basename "$service_file")"
    # Extract services array content (files now have proper 'services:' wrapper)
    sed -n '/^services:/,$ {
      /^services:/d
      p
    }' "$service_file" >> "$TEMP_FILE"
  fi
done

# Add a newline separator
echo "" >> "$TEMP_FILE"

# Combine all route definition files
echo "Adding routes..."
if grep -q "^routes:" "$CONFIG_DIR/routes"/*.yml 2>/dev/null; then
  echo "routes:" >> "$TEMP_FILE"
  for route_file in "$CONFIG_DIR/routes"/*.yml; do
    if [ -f "$route_file" ]; then
      echo "  - Adding routes from $(basename "$route_file")"
      # Extract routes array and indent properly
      sed -n '/^routes:/,/^[^ ]/ {
        /^routes:/d
        /^[^ ]/!p
      }' "$route_file" | sed 's/^  //' >> "$TEMP_FILE"
    fi
  done
  echo "" >> "$TEMP_FILE"
fi

# Add plugins section (consolidated)
echo "Adding plugins..."
echo "plugins:" >> "$TEMP_FILE"

# Add global plugins
if [ -f "$CONFIG_DIR/plugins/global-plugins.yml" ]; then
  echo "  - Adding global plugins"
  sed -n '/^plugins:/,$ {
    /^plugins:/d
    p
  }' "$CONFIG_DIR/plugins/global-plugins.yml" >> "$TEMP_FILE"
fi

# Add route-specific plugins (rate limiting, JWT, request transformer)
echo "Adding route-specific plugins..."
for plugin_file in "$CONFIG_DIR/plugins/rate-limiting.yml" \
                    "$CONFIG_DIR/plugins/jwt-auth.yml" \
                    "$CONFIG_DIR/plugins/request-transform.yml"; do
  if [ -f "$plugin_file" ]; then
    echo "  - Adding plugins from $(basename "$plugin_file")"
    # Extract plugins array content and append (skip the 'plugins:' line)
    sed -n '/^plugins:/,$ {
      /^plugins:/d
      p
    }' "$plugin_file" >> "$TEMP_FILE"
  fi
done

# Add custom quota-mirror plugin
echo "  - Adding quota-mirror plugin"
cat >> "$TEMP_FILE" <<EOF
  - name: quota-mirror
    enabled: true
    config:
      redis_host: redis
      redis_port: 6379
      redis_database: 0
      quota_key_prefix: "quota:tenant:"
      alert_threshold_percentage: 80.0
      enable_alerts: true
      block_on_quota_exceeded: false
      log_quota_checks: true
EOF

echo "" >> "$TEMP_FILE"

# Validate YAML syntax (if yq is available)
if command -v yq &> /dev/null; then
  echo "Validating YAML syntax..."
  if yq eval '.' "$TEMP_FILE" > /dev/null 2>&1; then
    echo "  ✓ YAML syntax valid"
  else
    echo "  ✗ YAML syntax error detected"
    exit 1
  fi
else
  echo "  ! yq not found, skipping YAML validation"
fi

# Move temp file to final location
mv "$TEMP_FILE" "$OUTPUT_FILE"

echo "✓ Kong configuration built successfully: $OUTPUT_FILE"
echo ""
echo "To apply configuration:"
echo "  docker-compose restart kong"
echo "  # OR via Kong Admin API:"
echo "  curl -X POST http://localhost:8001/config -F config=@$OUTPUT_FILE"
