_format_version: "3.0"

# Combined file for conftest validation (merges kong.yaml + allowed_provider_hosts.yaml)
allowed_hosts:
  - api.openai.com
  - api.anthropic.com
  - generativelanguage.googleapis.com
  - api.groq.com

services:
  - name: openai
    url: https://api.openai.com/v1
    tags: [r1, provider, allowlisted]
  - name: anthropic
    url: https://api.anthropic.com/v1
    tags: [r1, provider, allowlisted]
  - name: google-generative
    url: https://generativelanguage.googleapis.com/v1beta
    tags: [r1, provider, allowlisted]
  - name: groq
    url: https://api.groq.com/openai/v1
    tags: [r1, provider, allowlisted]

